### PR TITLE
Axiom Jakarta support finished

### PR DESCRIPTION
**Pull request by benothman**

### CODE REVIEW

**Comment by robertlazarski** [comment]
@veithen please review this pull request. We will need to release Axiom soon - before the next Axis2 release - so I suggest we make a decision here.

**Comment by veithen** [comment]
It looks like the change doesn't actually build. Also, I see a massive amount of code duplication. Would you mind summarizing what you are trying to achieve?

**Comment by benothman** [comment]
@veithen my goal is to have an axiom version which supports Jakarta XML instead of javax.
Spring WS 4.x has dropped the support of axiom because there is no Jakarta support.
However, would you mind pointing out the code duplication?
I created new modules to support Jakarta without removing the Javax ones.
thanks in advance for reviewing.

**Comment by veithen** [comment]
Basically your PR copies the code from `axiom-legacy-attachments` into a new module and replaces references to `javax` by `jakarta`. That's duplication because any change or bug fix to that code would need to be applied twice. Also, that change is rendered obsolete by one of @robertlazarski's commits which actually migrated `axiom-legacy-attachments` to the Jakarta APIs. His change makes sense because `axiom-legacy-attachments` is really just meant to be used by Axis2. Since Axis2 has now switched to the Jakarta APIs, we don't need a JavaEE version of `axiom-legacy-attachments` anymore.

As for Spring-WS, a future version that reinstates Axiom support should not depend on `axiom-legacy-attachments` at all.

**Pull request closed without merging**
